[PPABV-73] feat: add pm search transaction by date to test API collection
pagopa/pagopa-ecommerce-helpdesk-service pull request #167
Opened 2024-11-28 10:23 UTC by dylantangredi-bvt

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-11-29 09:23 UTC, FrancescoDiTonno-BVT submitted a review, later dismissed

2024-11-29 09:28 UTC, a-mannia requested changes
The dev API can be removed because the dev environment does not reach the DB PM

2024-11-29 09:35 UTC, a-mannia approved these changes

2024-11-29 15:12 UTC, infantesimone submitted a review, later dismissed

2024-12-03 10:42 UTC, a-mannia approved these changes

2024-12-03 17:30 UTC, infantesimone approved these changes

2024-12-03 17:30 UTC, merged